In [22]:
import numpy as np

al = np.array([2,3,4])

In [23]:
print(al.dtype)
print(al.ndim)
print(al.shape)
print(al.itemsize)
print(al.size)

int64
1
(3,)
8
3


In [24]:
al

array([2, 3, 4])

In [25]:
a2 = np.array([[2.0, 3, 4.0], [7, 8, 9], [10, 11, 12]], dtype=np.int8)

In [26]:
print(a2.dtype)
print(a2.ndim)
print(a2.shape)
print(a2.itemsize)
print(a2.size)

int8
2
(3, 3)
1
9


In [27]:
a3 = [0 for _ in range(600)]

In [ ]:
a3 = np.array(a3, dtype=np.int64)
a3 = a3.reshape((12, 5, 2, 5))
print(a3.dtype) #데이터 타입
print(a3.ndim) #차원 수
print(a3.shape) #구조
print(a3.itemsize) #요소 하나의 바이트 크기
print(a3.size) # 전체 요소 개수

int64
4
(12, 5, 2, 5)
8
600


In [29]:
ar1 = np.arange(27)  # [0, 27)
print(ar1)
ar2 = np.arange(1, 10.0001, 0.3)  # [1, 10)
print(ar2)
ar3 = np.linspace(1, 117, 35)
print(ar3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[ 1.   1.3  1.6  1.9  2.2  2.5  2.8  3.1  3.4  3.7  4.   4.3  4.6  4.9
  5.2  5.5  5.8  6.1  6.4  6.7  7.   7.3  7.6  7.9  8.2  8.5  8.8  9.1
  9.4  9.7 10. ]
[  1.           4.41176471   7.82352941  11.23529412  14.64705882
  18.05882353  21.47058824  24.88235294  28.29411765  31.70588235
  35.11764706  38.52941176  41.94117647  45.35294118  48.76470588
  52.17647059  55.58823529  59.          62.41176471  65.82352941
  69.23529412  72.64705882  76.05882353  79.47058824  82.88235294
  86.29411765  89.70588235  93.11764706  96.52941176  99.94117647
 103.35294118 106.76470588 110.17647059 113.58823529 117.        ]


In [30]:
np_list = []
np_list.append(np.zeros((3,4,5), dtype=np.int8))
# np_list.append(np.full((3,4,5), 132, dtype=np.int8))
np_list.append(np.eye(5, k = 1))
np_list.append(np.eye(5, k = 0))
np_list.append(np.diag(np_list[2], k = 1))
for npl in np_list:
    print(npl)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0. 0. 0. 0.]


In [31]:
b1 = np.ones_like(a3)
b2 = np.zeros_like(a3)
b3 = np.full_like(a3, 17)
print(b3)

[[[[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]]


 [[[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]]


 [[[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]]


 [[[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]]


 [[[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17 17 17 17 17]]

  [[17 17 17 17 17]
   [17

In [32]:
print(a2)
a3 = np.arange(9).reshape((3,3))
print(a3)
c1 = a2 + a3
c2 = a2 - a3
c3 = a2 / a3
print(c1,c2,c3)

# bool 연산
c4 = (a2 - 5) * 2 > a3
print(c4)

# bool 인덱싱
print(a2[c4])

[[ 2  3  4]
 [ 7  8  9]
 [10 11 12]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [10 12 14]
 [16 18 20]] [[2 2 2]
 [4 4 4]
 [4 4 4]] [[       inf 3.         2.        ]
 [2.33333333 2.         1.8       ]
 [1.66666667 1.57142857 1.5       ]]
[[False False False]
 [ True  True  True]
 [ True  True  True]]
[ 7  8  9 10 11 12]


/tmp/ipykernel_2438621/3018224684.py:6: RuntimeWarning: divide by zero encountered in divide
  c3 = a2 / a3
