Broadcasting

In [13]:
import numpy as np

In [14]:
a1 = np.linspace(1,12,12).reshape((3,4))
a2 = np.arange(1,5)
a3 = a2.reshape((4,1))
a4 = a1.reshape((3,1,4))

print(a1)
print(a2)
print(a3)
print(a4)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]]]


In [15]:
print(a1+a2)
print((a1+a2).shape)
print(a2+a3)
print((a2+a3).shape)
print(a1+a4)
print((a1+a4).shape)

[[ 2.  4.  6.  8.]
 [ 6.  8. 10. 12.]
 [10. 12. 14. 16.]]
(3, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
(4, 4)
[[[ 2.  4.  6.  8.]
  [ 6.  8. 10. 12.]
  [10. 12. 14. 16.]]

 [[ 6.  8. 10. 12.]
  [10. 12. 14. 16.]
  [14. 16. 18. 20.]]

 [[10. 12. 14. 16.]
  [14. 16. 18. 20.]
  [18. 20. 22. 24.]]]
(3, 3, 4)


Indexing

In [16]:
a1 = np.arange(1, 10+1) ** 2
a2 = a1[2:9]
print(a1,a2)
a1[3] = a1[1] + a1[2]
a2[:5:2] = 10_000
for i in range(len(a1)):
    print(a1[(i+1)*-1], end=', ')

[  1   4   9  16  25  36  49  64  81 100] [ 9 16 25 36 49 64 81]
100, 81, 64, 10000, 36, 10000, 13, 10000, 4, 1, 

In [17]:
a1 = np.fromfunction(lambda x, y, z : x+ y+ z,(2,5,4),dtype=np.int64)
a2 = a1[:,1::2,:3]

a2[1, ...] = -1

print(a1)

for ar in a2:
    print(ar)

[[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]
  [ 4  5  6  7]]

 [[ 1  2  3  4]
  [-1 -1 -1  5]
  [ 3  4  5  6]
  [-1 -1 -1  7]
  [ 5  6  7  8]]]
[[1 2 3]
 [3 4 5]]
[[-1 -1 -1]
 [-1 -1 -1]]


In [18]:
a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64)
a2 = np.arange(1, a1.size / 2 + 1).reshape(1, 5, 4) * 10
print(a1)
print(a2)

[[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]]]
[[[ 10.  20.  30.  40.]
  [ 50.  60.  70.  80.]
  [ 90. 100. 110. 120.]
  [130. 140. 150. 160.]
  [170. 180. 190. 200.]]]


In [ ]:
a3 = np.vstack((a1[0, ...], a2[0, ...]))
print(a3)
a4 = np.hstack((a1[0, ...], a2[0, ...]))
print(a4)
a5 = np.concatenate((a1, a2), 0)
print(a5)
a6 = np.concatenate((a1[0, ...], a2[0, ...]), 0)  # hstack
a7 = np.concatenate((a1[0, ...], a2[0, ...]), 1)  # vstack
print(a6)
print(a7)

[[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [130. 140. 150. 160.]
 [170. 180. 190. 200.]]
[[  0.   1.   2.   3.  10.  20.  30.  40.]
 [  1.   2.   3.   4.  50.  60.  70.  80.]
 [  2.   3.   4.   5.  90. 100. 110. 120.]
 [  3.   4.   5.   6. 130. 140. 150. 160.]
 [  4.   5.   6.   7. 170. 180. 190. 200.]]
[[[  0.   1.   2.   3.]
  [  1.   2.   3.   4.]
  [  2.   3.   4.   5.]
  [  3.   4.   5.   6.]
  [  4.   5.   6.   7.]]

 [[  1.   2.   3.   4.]
  [  2.   3.   4.   5.]
  [  3.   4.   5.   6.]
  [  4.   5.   6.   7.]
  [  5.   6.   7.   8.]]

 [[ 10.  20.  30.  40.]
  [ 50.  60.  70.  80.]
  [ 90. 100. 110. 120.]
  [130. 140. 150. 160.]
  [170. 180. 190. 200.]]]
[[  0.   1.   2.   3.  10.  20.  30.  40.]
 [  1.   2.   3.   4.  50.  60.  70.  80.]
 [  2.   3.   4.   5.  90. 100. 110. 120.]
 [  3.   4.   5.   6. 130. 140. 150. 160.]
 [  4.   5.   6

In [ ]:
a1 = np.arange(1,5)
a2 =